baseurl = "http://karateid.com"
languageCode = "id"
title = "Karate ID"
theme = "ananke"
googleAnalytics = ""

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  title = "Freddy Tjoenedi"
  description = "Informasi mengenai teknik dan sejarah karate atau bela diri pada umumnya."
  facebook = "https://www.facebook.com/karateid/"
  featured_image = ""

[taxonomies]
  tag = "tags"
  category = "categories"
